name: Build RPCSX Android

on:
  push:
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: "29.0.13113456"
      CMAKE_VERSION: "3.31.6"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        lfs: true

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install Ninja
      run: |
        sudo apt update
        sudo apt install -y ninja-build

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install packages
      run: yes | sdkmanager "cmake;${{ env.CMAKE_VERSION }}" "ndk;${{ env.NDK_VERSION }}"

    - name: Configure
      run: |
        $ANDROID_SDK_ROOT/cmake/${{ env.CMAKE_VERSION }}/bin/cmake \
          -B build -S android \
          -DANDROID_ABI=arm64-v8a \
          -DUSE_ARCH=armv8-a \
          -DANDROID_PLATFORM=android-29 \
          -DANDROID_NDK=$ANDROID_SDK_ROOT/ndk/${{ env.NDK_VERSION }} \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_SDK_ROOT/ndk/${{ env.NDK_VERSION }}/build/cmake/android.toolchain.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -G Ninja

    - name: Build
      run: |
        $ANDROID_SDK_ROOT/cmake/${{ env.CMAKE_VERSION }}/bin/cmake --build build
        $ANDROID_SDK_ROOT/ndk/${{ env.NDK_VERSION }}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip build/librpcsx-android.so
        mv build/librpcsx-android.so librpcsx-android-arm64-v8a.so

    - name: Upload .so artifact
      uses: actions/upload-artifact@v4
      with:
        name: rpcsx-android-so
        path: librpcsx-android-arm64-v8a.so
        if-no-files-found: error
